### ISSUE TITLE
 gcc: error: grep/src/kwset.c: No such file or directory

### ISSUE THREAD

**Issue by tseemann** [mcieslik-mctp/thecut#2]
```
gcc -g -Wall -Wextra -O3 -Wno-unused-function  -std=c99 -pedantic -pthread  -Ihtslib/htslib -Igrep -Igrep/lib -Igrep/src -Lgrep/lib -o hpscan_cw hpscan_cw.c grep/src/kwset.c -lgreputils -lz

gcc: error: grep/src/kwset.c: No such file or directory
```

**Comment by mcieslik-mctp** [comment]
I cannot reproduce. Did you follow the build instructions and do "make deps" before "make" ?

**Comment by tseemann** [comment]
That fixed it, sorry.  I thought I had all the dependencies installed, but I actually did not have a BUILD TIME "SOURCE" dep for `grep` which the above message indicates in retrospect.
